apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
  - name: storage
    readOnly: true
  steps:
    - name: cleanup
      image: kubiosec/hackon
      script: |
        #!/bin/bash
        echo "Completed"
