apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gh-issue
spec:
  params:
  - name: gh-url
    type: string
  - name: git-creds
    type: string
  - name: git-repo
    type: string
    default: repo
  - name: result-repo
    type: string
    default: result
  workspaces:
  - name: storage
    readOnly: false
  steps:
    - name: git-issue
      image: xxradar/ghcli:001
      env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: $(params.git-creds)
            key: gh-token
      script: |
        #!/bin/bash
        gh auth setup-git
        cd $(workspaces.storage.path)/$(params.git-repo)
        gh issue create --title "issue" -F $(workspaces.storage.path)/$(params.result-repo)/results.txt
