apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: fortidevsec-sast
spec:
  workspaces:
  - name: shared-data
  params:
  - name: gh-url
    type: string
  - name: git-creds
    type: string
  tasks:
    - name: gh-clone
      taskRef:
        name: gh-clone-fortidevsec
      params:
      - name: gh-url
        value: $(params.gh-url)
      - name: git-creds
        value: $(params.git-creds)
      workspaces:
      - name: storage
        workspace: shared-data
    - name: fortidevsec-sast
      taskRef:
        name: fortidevsec-sast
      runAfter:
        - gh-clone
      workspaces:
      - name: storage
        workspace: shared-data
    - name: cleanup
      taskRef:
        name: cleanup
      runAfter:
        - fortidevsec-sast
      workspaces:
      - name: storage
        workspace: shared-data
