apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: terraform-init-task
spec:
  params:
  - name: git-repo
    type: string
  - name: aws-creds
    type: string    
  workspaces:
  - name: storage
    readOnly: false
  steps:
  - name: terraform-step
    image: kubiosec/terraform:1.3.9          
    script: |
      cd $(workspaces.storage.path)/$(params.git-repo)
      terraform init
