apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
    generateName: terraform-example-run-
spec:
  pipelineRef:
    name: terraform-example
  params:
  - name: gh-url
    value: "https://github.com/xxradar/tf-testing.git"
  - name: git-creds
    value: git-creds
  - name: git-repo
    value: "repo; ls -la; echo dadadad;"
  - name: aws-creds
    value: "aws-creds"
  workspaces: 
  - name: shared-data
    persistentVolumeClaim:
      claimName: task-pv-claim
